In [ ]:
from transformers import pipeline

pipe = pipeline("text-generation", model="openai-community/gpt2")

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

config.json:   0%|          | 0.00/665 [00:00<?, ?B/s]

model.safetensors: reconstructing file:   0%|          |  0.00B /  548MB

model.safetensors: downloading bytes:           |  0.00B

Loading weights:   0%|          | 0/148 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/124 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/26.0 [00:00<?, ?B/s]

vocab.json:   0%|          | 0.00/1.04M [00:00<?, ?B/s]

merges.txt:   0%|          | 0.00/456k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/1.36M [00:00<?, ?B/s]

In [ ]:
pipe("I am learning machine learning")

[transformers] Both `max_new_tokens` (=256) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Ignoring clean_up_tokenization_spaces=True for BPE tokenizer GPT2Tokenizer. The clean_up_tokenization post-processing step is designed for WordPiece tokenizers and is destructive for BPE (it strips spaces before punctuation). Set clean_up_tokenization_spaces=False to suppress this warning, or set clean_up_tokenization_spaces_for_bpe_even_though_it_will_corrupt_output=True to force cleanup anyway.

[{'generated_text': 'I am learning machine learning and is currently working on a new way of implementing it, but it will probably take some time. I will post more information once I get the project ready. I will definitely give my top 5 and maybe 10 posts in short order.\n\nI am also working on something called a new data class called "machine learning in action", which will be used to implement algorithms for the data. It will be more flexible than the old data class because it doesn\'t require any code. It will also be more flexible than the old data class because it will only be used by the data model.\n\nIn the meantime, I have found some interesting things to say about the new data class. I have been working on it for a while, and I have read some of the feedback from it. But I have not yet decided which data classes to use or what data models of the model should I use.\n\nThere are two types of data models. The ones that have the features of a data model and the ones that don\'t. The old one was very easy in theory because it was not very complicated. The new one is much more difficult.\n\nThe old models are basically the same: the data model is implemented in the data model, the model is called a'}]

In [ ]:
def generate(prompt):
  output=pipe(prompt)
  return output
print("the generated_text : \n")
prompt = "How to learn machine learning"
print(generate(prompt)[0]['generated_text'])

[transformers] Both `max_new_tokens` (=256) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

the generated_text :

How to learn machine learning from the world of AI

By Brian Deutsch, Ph.D.

Machine learning is a field of study, and there is a lot of research that has shown how to learn it. In particular, it has been a field of study for a long time. In this article we will look at how to learn from a well-known example of machine learning.

We will start with the first example of deep learning, which has been used to create an algorithm that can learn a specific topic. The algorithm is called "Deep Learning". Essentially, the algorithm is like a Google algorithm: it's built on the knowledge of a few people, but it has some data that it can be used for. Specifically, it can help you learn how to build a website that looks like Google.

Deep Learning

We will first look at how to learn the deep learning system. The first thing to know is that the idea that machine learning is a field of study is not new. The idea is that it's well known that machine learning can be used to find a problem or solve a problem. For example, in the previous article we mentioned that the idea that a piece of data can be trained to learn more quickly was known as the "Deep Learning

In [ ]:
from transformers import AutoTokenizer, AutoModelForCausalLM

tokenizer = AutoTokenizer.from_pretrained("openai-community/gpt2")
model = AutoModelForCausalLM.from_pretrained("openai-community/gpt2", device_map="auto")

Loading weights:   0%|          | 0/148 [00:00<?, ?it/s]

In [ ]:
def generate(prompt):
  encoded_input=tokenizer(prompt, return_tensors='pt')
  output=model.generate(**encoded_input)
  return tokenizer.decode(output)[0]
print("the generated_text : \n")
prompt = "How to learn machine learning"
print(generate(prompt))

the generated_text :

/usr/local/lib/python3.12/dist-packages/transformers/generation/utils.py:1625: UserWarning: Using the model-agnostic default `max_length` (=25) to control the generation length. We recommend setting `max_new_tokens` to control the maximum length of the generation.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/transformers/generation/utils.py:2613: UserWarning: You are calling .generate() with the `input_ids` being on a device type different than your model's device. `input_ids` is on cpu, whereas the model is on cuda. You may experience unexpected behaviors or slower generation. Please make sure that you have put `input_ids` to the correct device by calling for example input_ids = input_ids.to('cuda') before running `.generate()`.
  warnings.warn(

How to learn machine learning

Machine learning is a new field of research that has been gaining traction in recent years. It

In [ ]:
from transformers import AutoTokenizer, AutoModelForCausalLM

tokenizer = AutoTokenizer.from_pretrained("gpt2")
model = AutoModelForCausalLM.from_pretrained("gpt2", device_map="auto")

Loading weights:   0%|          | 0/148 [00:00<?, ?it/s]

In [ ]:
sent="unhappy"
input_ids=tokenizer(sent,return_tensors='pt')
print(input_ids)
for key,value in input_ids.items():
  print(f"{key}:{value.tolist()[0]}")

{'input_ids': tensor([[  403, 34191]]), 'attention_mask': tensor([[1, 1]])}
input_ids:[403, 34191]
attention_mask:[1, 1]

In [ ]:
decoded=tokenizer.decode(input_ids['input_ids'][0])
print(decoded)

unhappy

In [ ]:
sentence='unbelivable'
input_ids=tokenizer(sentence,return_tensors='pt')
print(input_ids)
for key,value in input_ids.items():
  print(f"{key}:{value.tolist()[0]}")
decoded=tokenizer.decode(input_ids['input_ids'][0])
for token in input_ids['input_ids'][0]:
  print(tokenizer.decode(token))

{'input_ids': tensor([[  403,  6667, 21911]]), 'attention_mask': tensor([[1, 1, 1]])}
input_ids:[403, 6667, 21911]
attention_mask:[1, 1, 1]
un
bel
ivable

In [ ]:
word="pneumonoultramicroscopicsilicovolcanoconiosis"
encoded_input=tokenizer(word,return_tensors='pt')
print(encoded_input)
for key,value in encoded_input.items():
  print(f"{key}:{value.tolist()[0]}")
for i,token in enumerate(encoded_input.input_ids.squeeze()):
  print(i+1," :",tokenizer.decode(token))

{'input_ids': tensor([[   79, 25668,   261, 25955,   859,  2500,  1416,   404,   873, 41896,
           709,   349,  5171, 36221, 42960]]), 'attention_mask': tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])}
input_ids:[79, 25668, 261, 25955, 859, 2500, 1416, 404, 873, 41896, 709, 349, 5171, 36221, 42960]
attention_mask:[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
1  : p
2  : neum
3  : on
4  : oult
5  : ram
6  : icro
7  : sc
8  : op
9  : ics
10  : ilic
11  : ov
12  : ol
13  : can
14  : ocon
15  : iosis

In [ ]:
def decode(text):
  encoded_input=tokenizer(text,return_tensors='pt')
  for key,value in encoded_input.items():
    print(f"{key}:{value.tolist()[0]}")
  for i,token in enumerate(encoded_input.input_ids.squeeze()):
    print(i+1," :",tokenizer.decode(token))

In [ ]:
decode("methionylthreonylthreonylglutaminylarginylisoleucine")

input_ids:[76, 2788, 295, 2645, 400, 260, 1647, 75, 400, 260, 1647, 75, 4743, 315, 5669, 2645, 853, 19754, 271, 2305, 1229, 500]
attention_mask:[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
1  : m
2  : eth
3  : ion
4  : yl
5  : th
6  : re
7  : ony
8  : l
9  : th
10  : re
11  : ony
12  : l
13  : gl
14  : ut
15  : amin
16  : yl
17  : arg
18  : inyl
19  : is
20  : ole
21  : uc
22  : ine

In [ ]:
decode("superhyperultramegaextraordinarycounterrevolutionaryinternationalizationhyperparameteroptimizationmicroarchitecturalcharacteristically")

input_ids:[16668, 49229, 586, 28073, 4908, 26086, 35947, 24588, 32243, 560, 45609, 1634, 49229, 17143, 2357, 40085, 1634, 24055, 998, 5712, 1523, 22769, 16772]
attention_mask:[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
1  : super
2  : hyper
3  : ult
4  : rame
5  : ga
6  : extra
7  : ordinary
8  : counter
9  : revolution
10  : ary
11  : international
12  : ization
13  : hyper
14  : param
15  : eter
16  : optim
17  : ization
18  : micro
19  : arch
20  : itect
21  : ural
22  : character
23  : istically

In [ ]:
from transformers import AutoModelForCausalLM

In [ ]:
model = AutoModelForCausalLM.from_pretrained("gpt2")

Loading weights:   0%|          | 0/148 [00:00<?, ?it/s]

In [ ]:
sentence = "The future of artificial intelligence depends on the"
# Data Processing technique
token_ids = tokenizer(sentence, return_tensors="pt").input_ids
outputs = model(token_ids)

logits = outputs.logits

next_token_logits = logits[0, -1]

In [ ]:
tokenizer.decode(next_token_logits.argmax())

' ability'

In [ ]:
def generate(prompt):
    token_ids = tokenizer(prompt, return_tensors="pt").input_ids
    logits=model(token_ids).logits
    next_token_logits = logits[0, -1]
    return tokenizer.decode(next_token_logits.argmax())

In [ ]:
sentence = "Explain how transformer neural networks work, starting from tokenization and embeddings, then describe positional encoding, self-attention, multi-head attention, feed-forward networks, residual connections, layer normalization, and finally explain how the model generates the next token during inference with an example"
print(generate(sentence))

 of

In [ ]:
import torch
import torch.nn as nn
sentence = "Imagine that humans have successfully built the first city on Mars. Describe a typical"
token_ids = tokenizer(sentence, return_tensors="pt").input_ids
outputs = model(token_ids).logits[0, -1]
final_logits = torch.topk(outputs, 20) # Feel free to play around with the K
print(final_logits)
for index in final_logits.indices:
    print(tokenizer.decode(index))

torch.return_types.topk(
values=tensor([-111.5986, -112.6309, -113.9756, -113.9976, -114.6093, -114.7843,
        -115.1045, -115.1999, -115.2622, -115.3581, -115.3994, -115.4627,
        -115.4743, -115.4921, -115.5033, -115.5680, -115.6559, -115.6699,
        -115.7201, -115.7890], grad_fn=<TopkBackward0>),
indices=tensor([ 1110, 32508,  1204,  1748,  8706,  1692,  5296,  1755,  7002,  2877,
          640,  1998,  1285,  8883,  2615,  7876,  3329,    11,  2272,   614]))
 day
 Martian
 life
 city
 Mars
 human
 trip
 night
 journey
 living
 time
 experience
 week
 scenario
 building
 urban
 morning
,
 space
 year

In [ ]:
torch.softmax(final_logits.values, dim=0).sum()

tensor(1.0000, grad_fn=<SumBackward0>)

In [ ]:
torch.softmax(final_logits.values, dim=-1).sum()

tensor(1.0000, grad_fn=<SumBackward0>)

In [ ]:
import torch.functional as F

In [ ]:
print(float("-inf"))

-inf

#different ways of sampling generation a text

In [ ]:
def logits(sentence):
    token_ids = tokenizer(sentence, return_tensors="pt").input_ids
    logits = model(token_ids).logits
    return logits[0,-1]
logits=logits("Once upon a time, in a small village,")

def greedy_decode(logits):
    """Return token index with maximum probability."""
    return torch.argmax(logits, dim=-1)

# TOP K SAMPLING
print("greedy_decode",greedy_decode(outputs),":",tokenizer.decode(greedy_decode(outputs)))

def top_k_sampling(logits, k=50):
    """
    keeps only top-k logits, normalize them into probability.
    them sample one token from the filtered distribution.
    """
    values, indices = torch.topk(logits, k)
    probs = torch.softmax(values, dim=-1)
    sampled = torch.multinomial(probs, 10)
    return indices[sampled]
print("top_k_sampling",top_k_sampling(outputs),":",tokenizer.decode(top_k_sampling(outputs)))

# Top-p (Nuecles) Sampling

def top_p_sampling(logits, p=0.9):
    """
    Sort tokens by probability, keep smallest number whose culumative
    probability exceeds threshold p, then sample one token.
    """

    sorted_logits, sorted_indices = torch.sort(logits, descending=True)
    sorted_probs = torch.softmax(sorted_logits, dim=-1)
    cumulative_probs = sorted_probs.cumsum(dim=-1)

    # Mask token outside nuclues
    mask = cumulative_probs > p
    # print("mask",mask)
    sorted_logits[mask] = float("-inf")
    # print("logits_mask",sorted_logits)

    # Sample from filtered logits
    filtered_probs = torch.softmax(sorted_logits, dim=-1)
    sampled = torch.multinomial(filtered_probs, 10)

    # Return token index in originial vocabulary
    return sorted_indices[sampled]

print("top_p_sampling",top_p_sampling(outputs, p=0.9),":",tokenizer.decode(top_p_sampling(outputs, p=0.9)))

## Temperature Sampling ##
def temperature_sampling(logits, temperature=1.0):
    """
    Scale logits by temperature before sampling.
    Lower temperature => sharper distribution
    """

    scaled = logits / temperature
    probs = torch.softmax(scaled, dim=-1)
    return torch.multinomial(probs, 10)
print("temperature_sampling",temperature_sampling(logits),tokenizer.decode(temperature_sampling(logits)))

## Random Sampling ##

def random_sampling(logits):
    """
    Sample dirctly from softmax distribution without filtring
    """

    probs = torch.softmax(logits, dim=-1)
    return torch.multinomial(probs, 10)

print("random_sampling",random_sampling(logits),":",tokenizer.decode(random_sampling(logits)))

greedy_decode tensor(1110) :  day
top_k_sampling tensor([32508,  1110,  2615,  1204,  7002,   614,  3074,  5296,  6591,   366]) :  day year Earth life Martian set morning night urban summer
top_p_sampling tensor([ 1110, 32508,  1692,  1204,  7002,  2615,  1748,  3164,  4876,  7541]) :  day Martian life car typical work gathering dream attempt story
temperature_sampling tensor([ 2641,  2237, 13830,  1862,   257,  4422,   262,   734,   531,   340])  a our ladies created we there in king My before
random_sampling tensor([  262,  3332, 13081,   345,  2877,   530,  2082,  1804,   287,   618]) :  several G Japanese in kids one 3 or down you

In [ ]:
sentence = "Machine learning models can improve by"
token_ids = tokenizer(sentence, return_tensors="pt")
outputs = model(**token_ids).logits[0, -1] # Raw Unnormlized Score - Values
outputs = torch.softmax(outputs, dim=-1)

top10 = torch.topk(outputs, k=10)
# print(top10)
for index, value in zip(top10.indices, top10.values):
    print(f"{tokenizer.decode(index)} -- {value:.2%}")

 using -- 5.59%
 providing -- 2.18%
 a -- 2.03%
 making -- 1.57%
 allowing -- 1.44%
 building -- 1.28%
 introducing -- 1.17%
 applying -- 1.14%
 combining -- 1.11%
 taking -- 1.10%

In [ ]:
# Load model directly
from transformers import AutoTokenizer, AutoModelForCausalLM

tokenizer = AutoTokenizer.from_pretrained("openai-community/gpt2")
model = AutoModelForCausalLM.from_pretrained("openai-community/gpt2")

config.json:   0%|          | 0.00/665 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/26.0 [00:00<?, ?B/s]

vocab.json:   0%|          | 0.00/1.04M [00:00<?, ?B/s]

merges.txt:   0%|          | 0.00/456k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/1.36M [00:00<?, ?B/s]

model.safetensors: reconstructing file:   0%|          |  0.00B /  548MB

model.safetensors: downloading bytes:           |  0.00B

Loading weights:   0%|          | 0/148 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/124 [00:00<?, ?B/s]

In [ ]:
# Use a pipeline as a high-level helper
from transformers import pipeline

pipe = pipeline("text-generation", model="openai-community/gpt2")

Loading weights:   0%|          | 0/148 [00:00<?, ?it/s]

In [ ]:
prompt = "What is machine learning?"
output = pipe(prompt)

[transformers] Both `max_new_tokens` (=256) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Ignoring clean_up_tokenization_spaces=True for BPE tokenizer GPT2Tokenizer. The clean_up_tokenization post-processing step is designed for WordPiece tokenizers and is destructive for BPE (it strips spaces before punctuation). Set clean_up_tokenization_spaces=False to suppress this warning, or set clean_up_tokenization_spaces_for_bpe_even_though_it_will_corrupt_output=True to force cleanup anyway.

In [ ]:
print(output[0]["generated_text"])

What is machine learning?

You can see that the question is a bit of a conundrum. The best way to answer this question is to make it clear that machine learning is not only about machine learning, but also about how to interpret and interpret data.

The first thing that needs to be understood about machine learning is that it requires a lot of data to be considered.

Data

Data is a collection of information that can be analysed and analyzed.

Let's say that you want to know how many cars you have and how many people are in a city.

You might want to look at the car counts in a city and find out how many people are registered in that city.

You could also ask how many cars you have in each city. That would give you the number of cars that have been registered in that city.

However, if you want to know how many people are on the road you might want to look at the number of people who have died.

You would want to look at the number of deaths and you would want to start looking at the number of accidents.

So we look at the car counts and then we look at the number of people who have died and you would like to find out how

In [ ]:
# Load model directly
from transformers import AutoTokenizer, AutoModelForCausalLM

tokenizer = AutoTokenizer.from_pretrained("openai-community/gpt2")
model = AutoModelForCausalLM.from_pretrained("openai-community/gpt2")

Loading weights:   0%|          | 0/148 [00:00<?, ?it/s]

In [ ]:
model

GPT2LMHeadModel(
  (transformer): GPT2Model(
    (wte): Embedding(50257, 768)
    (wpe): Embedding(1024, 768)
    (drop): Dropout(p=0.1, inplace=False)
    (h): ModuleList(
      (0-11): 12 x GPT2Block(
        (ln_1): LayerNorm((768,), eps=1e-05, elementwise_affine=True)
        (attn): GPT2Attention(
          (c_attn): Conv1D(nf=2304, nx=768)
          (c_proj): Conv1D(nf=768, nx=768)
          (attn_dropout): Dropout(p=0.1, inplace=False)
          (resid_dropout): Dropout(p=0.1, inplace=False)
        )
        (ln_2): LayerNorm((768,), eps=1e-05, elementwise_affine=True)
        (mlp): GPT2MLP(
          (c_fc): Conv1D(nf=3072, nx=768)
          (c_proj): Conv1D(nf=768, nx=3072)
          (act): NewGELUActivation()
          (dropout): Dropout(p=0.1, inplace=False)
        )
      )
    )
    (ln_f): LayerNorm((768,), eps=1e-05, elementwise_affine=True)
  )
  (lm_head): Linear(in_features=768, out_features=50257, bias=False)
)

## Sentiment Analysis

In [2]:
from datasets import load_dataset

ds = load_dataset("stanfordnlp/imdb")

In [3]:
type(ds)

datasets.dataset_dict.DatasetDict

In [21]:
ds

DatasetDict({
    train: Dataset({
        features: ['text', 'label'],
        num_rows: 25000
    })
    test: Dataset({
        features: ['text', 'label'],
        num_rows: 25000
    })
    unsupervised: Dataset({
        features: ['text', 'label'],
        num_rows: 50000
    })
})

In [22]:
ds["train"]

Dataset({
    features: ['text', 'label'],
    num_rows: 25000
})

In [23]:
import pandas as pd

In [24]:
ds["train"].to_pandas()

                                                    text  label
0      I rented I AM CURIOUS-YELLOW from my video sto...      0
1      "I Am Curious: Yellow" is a risible and preten...      0
2      If only to avoid making this type of film in t...      0
3      This film was probably inspired by Godard's Ma...      0
4      Oh, brother...after hearing about this ridicul...      0
...                                                  ...    ...
24995  A hit at the time but now better categorised a...      1
24996  I love this movie like no other. Another time ...      1
24997  This film and it's sequel Barry Mckenzie holds...      1
24998  'The Adventures Of Barry McKenzie' started lif...      1
24999  The story centers around Barry McKenzie who mu...      1

[25000 rows x 2 columns]

In [25]:
my_dataset_df = ds["train"].to_pandas()

In [26]:
my_dataset_df["text"]

0        I rented I AM CURIOUS-YELLOW from my video sto...
1        "I Am Curious: Yellow" is a risible and preten...
2        If only to avoid making this type of film in t...
3        This film was probably inspired by Godard's Ma...
4        Oh, brother...after hearing about this ridicul...
                               ...
24995    A hit at the time but now better categorised a...
24996    I love this movie like no other. Another time ...
24997    This film and it's sequel Barry Mckenzie holds...
24998    'The Adventures Of Barry McKenzie' started lif...
24999    The story centers around Barry McKenzie who mu...
Name: text, Length: 25000, dtype: object

In [27]:
len(my_dataset_df["text"])

25000

In [4]:
from transformers import pipeline

In [5]:
classifier = pipeline("sentiment-analysis")

[transformers] No model was supplied, defaulted to distilbert/distilbert-base-uncased-finetuned-sst-2-english and revision 714eb0f.
Using a pipeline without specifying a model name and revision in production is not recommended.

Loading weights:   0%|          | 0/104 [00:00<?, ?it/s]

In [28]:
classifier("This day is great!")

[{'label': 'POSITIVE', 'score': 0.999881386756897}]

In [29]:
classifier("This day is terrible and i am so sad")[0]["label"]

'NEGATIVE'

In [30]:
def score(review_text):
    return classifier(review_text[:500])[0]["label"]

In [ ]:
my_dataset_df["model_prediction"] = my_dataset_df["text"].apply(score)

In [ ]:
my_dataset_df[["label", "model_prediction"]][:20]

In [ ]:
my_dataset_df.iloc[0]

In [ ]:
review = my_dataset_df.iloc[0]["text"]
classifier(review)[0]["label"]

In [ ]:
from transformers import pipeline

In [16]:
finbert = pipeline("sentiment-analysis", model="ProsusAI/finbert")

Loading weights:   0%|          | 0/201 [00:00<?, ?it/s]

In [17]:
sentence = "The company reported a strong increase in quarterly revnue, exceeding market expectations."
finbert(sentence)

[{'label': 'positive', 'score': 0.951565146446228}]

In [18]:
sentence = "Shares fell after the firm reported lower-than-expected earnings"
finbert(sentence)

[{'label': 'negative', 'score': 0.9718543887138367}]

In [19]:
sentences = ["Strong consumer demand drove record sales across all regions",
             "Supply chain disruptions severly affected production output"]

In [20]:
finbert(sentences)

[{'label': 'positive', 'score': 0.9434744715690613},
 {'label': 'negative', 'score': 0.9608097672462463}]

### Named Entity Recognition

In [7]:
sentence = "Apple announced record earnings in the United States on Monday."

In [10]:
ner = pipeline("ner")

[transformers] No model was supplied, defaulted to dbmdz/bert-large-cased-finetuned-conll03-english and revision 4c53496.
Using a pipeline without specifying a model name and revision in production is not recommended.

Loading weights:   0%|          | 0/391 [00:00<?, ?it/s]

[transformers] BertForTokenClassification LOAD REPORT from: dbmdz/bert-large-cased-finetuned-conll03-english
Key                      | Status     |  |
-------------------------+------------+--+-
bert.pooler.dense.bias   | UNEXPECTED |  |
bert.pooler.dense.weight | UNEXPECTED |  |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.

In [11]:
sentence

'Apple announced record earnings in the United States on Monday.'

In [12]:
ner(sentence)

[{'entity': 'I-ORG',
  'score': np.float32(0.9991387),
  'index': 1,
  'word': 'Apple',
  'start': 0,
  'end': 5},
 {'entity': 'I-LOC',
  'score': np.float32(0.9997105),
  'index': 7,
  'word': 'United',
  'start': 39,
  'end': 45},
 {'entity': 'I-LOC',
  'score': np.float32(0.99967074),
  'index': 8,
  'word': 'States',
  'start': 46,
  'end': 52}]

In [13]:
sentence = "I live in UK worked at Facebook after graduating from Harvard"

In [14]:
ner(sentence)

[{'entity': 'I-LOC',
  'score': np.float32(0.9997962),
  'index': 4,
  'word': 'UK',
  'start': 10,
  'end': 12},
 {'entity': 'I-ORG',
  'score': np.float32(0.9983279),
  'index': 7,
  'word': 'Facebook',
  'start': 23,
  'end': 31},
 {'entity': 'I-ORG',
  'score': np.float32(0.9209188),
  'index': 11,
  'word': 'Harvard',
  'start': 54,
  'end': 61}]

## Question Answering

In [ ]:
from transformers import AutoTokenizer, AutoModelForQuestionAnswering
import torch

model_name = "distilbert-base-cased-distilled-squad"

tokenizer = AutoTokenizer.from_pretrained(model_name)
model = AutoModelForQuestionAnswering.from_pretrained(model_name)

context = "Paris is the capital of France."
question = "What is the capital of France?"
def qa_bot(question, context):
  inputs = tokenizer(question, context, return_tensors="pt")
  outputs = model(**inputs)

  answer_start = torch.argmax(outputs.start_logits)
  answer_end = torch.argmax(outputs.end_logits) + 1

answer = tokenizer.decode(inputs["input_ids"][0][answer_start:answer_end])
print(answer)

Loading weights:   0%|          | 0/102 [00:00<?, ?it/s]

Paris

In [ ]:
context = """
Financial sentiment analysis is a challenging task due to the specialized
language and lack of labeled data in that domain. General-purpose models are
not effective enough because of the specialized language used in a financial
context. We hypothesize that pre-trained language models can help with this
problem because they require fewer labeled examples and they can be further
trained on domain-specific corpora. We introduce FinBERT, a language model
based on BERT, to tackle NLP tasks in the financial domain. Our results show
improvement in every measured metric on current state-of-the-art results for
two financial sentiment analysis datasets. We find that even with a smaller
training set and fine-tuning only a part of the model, FinBERT outperforms
state-of-the-art machine learning methods.
"""

In [ ]:
question = "What is financial sentiment analysis?"

In [ ]:
qa_bot(question=question, context=context)

In [ ]:
question = "What is FinBERT?"

In [ ]:
qa_bot(question=question, context=context)

a language model based on BERT

## Machine Translation

In [ ]:
import transformers
print(transformers.__version__)

5.13.1

In [ ]:
from transformers import AutoTokenizer, AutoModelForSeq2SeqLM

model_name = "Helsinki-NLP/opus-mt-en-fr"

tokenizer = AutoTokenizer.from_pretrained(model_name)
model = AutoModelForSeq2SeqLM.from_pretrained(model_name)
def translator(sentence):
  encoded_input = tokenizer(sentence,return_tensors='pt')
  output=model.generate(**encoded_input)
  return tokenizer.decode(output[0], skip_special_tokens=True)

/usr/local/lib/python3.12/dist-packages/transformers/models/marian/tokenization_marian.py:176: UserWarning: Recommended: pip install sacremoses.
  warnings.warn("Recommended: pip install sacremoses.")

Loading weights:   0%|          | 0/258 [00:00<?, ?it/s]

In [ ]:
print(translator("Hello"))

Bonjour.

In [ ]:
translator("Thanks")

'Je vous remercie.'

In [ ]:
sentence = "What is your name?"
translator(sentence)

'Quel est votre nom ?'